/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
    kotlin("plugin.serialization") version "2.2.21"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    api(project(":void-base"))
    api(project(":void-json"))
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test.junit5)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation("org.bouncycastle:bcpkix-jdk18on:1.82")
}

tasks.test {
    // Tell Gradle to use the JUnit Platform (JUnit 5)
    useJUnitPlatform()

    // optional: don't fail the build if no tests discovered (useful while configuring)
    // change to 'true' if you want the build to fail when there are zero tests discovered
    failOnNoDiscoveredTests = false

    // helpful logging during initial debugging
    testLogging {
        events("passed", "skipped", "failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = true
    }
}

description = "test"
