/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    // repositories used to resolve Gradle plugins (kotlin("jvm") etc.)
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        // add any private plugin repo here:
        // maven { url = uri("https://my.company.repo/plugins") }
    }
}

dependencyResolutionManagement {
    // control repositories for project dependencies
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT) // optional, forbids repos in subprojects
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url = uri("https://repo.maven.apache.org/maven2/")
        }
    }
}

rootProject.name = "void-framework"
include(":test")
include(":void-base")

include(":void-html")
include(":void-json")
include(":docs")
